"""Clarify-once conversations built from MEVA ground truth that already exists in eval/queries.

Each camera gets an invented place name. The first question about a place must trigger one clarification (the
scripted answer binds the place to the camera); every later question about it must not, including three fixed
rewordings of the name. The camera is never named in these questions, so a correct answer shows that the
referent survived the clarification. Ground truth (hits, negatives) is copied from the capability queries, so
nothing new is claimed about MEVA's labels.

    python scripts/meva_conversation_queries.py --out eval/queries_extended/meva_conversations.yaml

Rewordings are fixed here, before any result is seen: dropping the article, adding "area", changing the case.
Run the result on a fresh copy of the workspace each time: answers are remembered in its database.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

PLACES = {  # MEVA camera code -> invented place name (arbitrary on purpose: no model can know them)
    "G299": "east corridor", "G300": "north lawn", "G328": "front lot", "G330": "annex path", "G419": "side door",
    "G421": "back entrance", "G423": "loading bay", "G424": "courtyard",
}
REWORDINGS = (  # (tag, function of the place name)
    ("no_article", lambda p: p),
    ("area", lambda p: f"the {p} area"),
    ("case", lambda p: f"The {p.title()}"),
)
CAMERA = re.compile(r"G\d+")


def _ask(text: str, spelled: str) -> str:
    """'Was there a person on G299 between ...' -> 'Was there a person at <spelled> between ...'."""
    return re.sub(r"\bon G\d+\b", f"at {spelled}", text)


def build(source: list[dict[str, Any]], camera_map: dict[str, str]) -> list[dict[str, Any]]:
    by_cam: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in source:
        cam = next((t for t in item["tags"] if CAMERA.fullmatch(t)), None)
        if cam in PLACES and cam in camera_map:
            by_cam[cam].append(item)
    out: list[dict[str, Any]] = []
    for cam in sorted(by_cam):
        place = f"the {PLACES[cam]}"
        positives = [i for i in by_cam[cam] if i["expected"]["verdict"] == "yes"]
        negatives = [i for i in by_cam[cam] if i["expected"]["verdict"] == "no"]
        script: list[tuple[dict[str, Any], str, str]] = []  # (ground truth item, spelled place, tag)
        if not positives and not negatives:
            continue
        pool = positives + negatives
        script.append((pool[0], place, "first_mention"))
        if len(pool) > 1:
            script.append((pool[1], place, "same_wording"))
        for k, (tag, fn) in enumerate(REWORDINGS):
            gt = pool[(k + 2) % len(pool)]
            script.append((gt, fn(PLACES[cam]), f"reworded_{tag}"))
        for n, (gt, spelled, tag) in enumerate(script):
            first = n == 0
            item = {
                "id": f"conv_{cam}_{n}_{tag}",
                "text": _ask(gt["text"], spelled),
                "workspace": gt["workspace"], "intent": "exists",
                "expected": {"verdict": gt["expected"]["verdict"],
                            "hits": [{**h, "camera_id": camera_map[cam]} for h in gt["expected"]["hits"]]},
                "tags": ["meva", "cap:conversation", cam, tag, "cap:object" if gt["expected"]["hits"] else "cap:negative"],
                "split": gt["split"],
            }
            if first:
                item["first_time_requires_clarify"] = [PLACES[cam]]
                item["clarify_answer"] = {"camera_id": camera_map[cam]}
            out.append(item)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", type=Path, default=Path("eval/queries/meva_capabilities.yaml"))
    parser.add_argument("--camera-map", type=Path, default=Path("eval/meva_school_cameras.json"))
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    source = yaml.safe_load(args.source.read_text(encoding="utf-8"))
    items = build(source, json.loads(args.camera_map.read_text(encoding="utf-8")))
    if not items:
        print("no conversations could be built", file=sys.stderr)
        return 2
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("# generated by scripts/meva_conversation_queries.py; ground truth copied from the capability queries\n"
                        + yaml.safe_dump(items, sort_keys=False, allow_unicode=True, width=120), encoding="utf-8")
    splits: dict[str, int] = defaultdict(int)
    for it in items:
        splits[it["split"]] += 1
    print(f"{len(items)} queries, {sum(1 for i in items if 'first_time_requires_clarify' in i)} first mentions -> {args.out}")
    print("by split:", ", ".join(f"{k} {v}" for k, v in sorted(splits.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
