/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EvoraContracts {
  Evidence: Evidence;
  Alert: Alert;
  PathHop: PathHop;
  QueryPlan: QueryPlan;
  Referent: Referent;
  Target: Target;
  TimeWindow: TimeWindow;
  Answer: Answer;
  CameraInfo: CameraInfo;
  CameraOption: CameraOption;
  ClarifyRequest: ClarifyRequest;
  Zone: Zone;
  ClarifyResponse: ClarifyResponse;
  IngestJob: IngestJob;
  MemoryFact: MemoryFact;
  StandingQuery: StandingQuery;
  StreamEvent: StreamEvent;
  TrackAttrs: TrackAttrs;
}
export interface Evidence {
  id: string;
  camera_id: string;
  camera_name: string;
  t_start: number;
  t_end: number;
  t_peak: number;
  offset_s: number;
  track_id?: string | null;
  global_id?: string | null;
  bbox?: [number, number, number, number] | null;
  thumb_url: string;
  clip_url: string;
  score: number;
  verified?: boolean | null;
  why?: string[];
  [k: string]: unknown;
}
export interface Alert {
  id: string;
  standing_query_id: string;
  t: number;
  camera_id: string;
  evidence: Evidence;
  acknowledged?: boolean;
  [k: string]: unknown;
}
export interface PathHop {
  camera_id: string;
  camera_name: string;
  t_in: number;
  t_out: number;
  evidence_id: string;
  [k: string]: unknown;
}
export interface QueryPlan {
  intent: "exists" | "list" | "count" | "first" | "last" | "path" | "describe" | "standing";
  targets?: Target[];
  place?: Referent | null;
  action?: "any" | "pass_through" | "enter" | "exit" | "dwell" | "appear";
  time?: TimeWindow | null;
  camera_ids?: string[];
  limit?: number;
  unresolved?: Referent[];
  source?: "fastpath" | "llm" | "local_llm" | "cache";
  [k: string]: unknown;
}
export interface Target {
  noun: string;
  cls?: string[];
  attributes?: string[];
  embed_text: string;
  example_track_id?: string | null;
  [k: string]: unknown;
}
export interface Referent {
  text: string;
  role: "place" | "object" | "time";
  [k: string]: unknown;
}
export interface TimeWindow {
  start?: number | null;
  end?: number | null;
  phrase?: string | null;
  tod_after?: string | null;
  tod_before?: string | null;
  [k: string]: unknown;
}
export interface Answer {
  query_id: string;
  text: string;
  verdict: "yes" | "no" | "found" | "not_found" | "partial" | "count";
  count?: number | null;
  evidence?: Evidence[];
  path?: PathHop[];
  nearest_miss?: Evidence | null;
  confidence: number;
  plan: QueryPlan;
  timings_ms?: {
    [k: string]: number;
  };
  notes?: string[];
  unsupported_action?: string | null;
  [k: string]: unknown;
}
export interface CameraInfo {
  id: string;
  name: string;
  kind: "file" | "rtsp";
  source_uri: string;
  fps?: number | null;
  width?: number | null;
  height?: number | null;
  t0: number;
  t0_source: "filename" | "metadata" | "osd" | "slate" | "manual" | "live";
  duration_s?: number | null;
  site_xy?: [number, number] | null;
  status?: "pending" | "ingesting" | "ready" | "live" | "error";
  layers?: ("L0" | "L1" | "L2" | "L3")[];
  ir_fraction?: number | null;
  [k: string]: unknown;
}
export interface CameraOption {
  camera_id: string;
  camera_name: string;
  thumb_url: string;
  [k: string]: unknown;
}
export interface ClarifyRequest {
  query_id: string;
  referent: Referent;
  question: string;
  kind: "choose_camera" | "choose_known" | "choose_track" | "time_range";
  options?: CameraOption[];
  known_candidates?: string[];
  allow_region?: boolean;
  [k: string]: unknown;
}
export interface Zone {
  id: string;
  camera_id: string;
  kind: "line" | "polygon" | "frame";
  points?: [number, number][];
  direction?: "any" | "a_to_b" | "b_to_a";
  [k: string]: unknown;
}
export interface ClarifyResponse {
  query_id: string;
  camera_id?: string | null;
  zone?: Zone | null;
  fact_id?: string | null;
  track_id?: string | null;
  tod_after?: string | null;
  tod_before?: string | null;
  text?: string | null;
  [k: string]: unknown;
}
export interface IngestJob {
  id: string;
  camera_id: string;
  state: "queued" | "running" | "done" | "error";
  layer?: ("L0" | "L1" | "L2" | "L3") | null;
  progress?: number;
  video_s_per_s?: number | null;
  error?: string | null;
  [k: string]: unknown;
}
export interface MemoryFact {
  id: string;
  kind: "place" | "object" | "time";
  canonical: string;
  aliases?: string[];
  inferred_aliases?: string[];
  binding: {
    [k: string]: unknown;
  };
  source: "clarification" | "statement" | "correction" | "import";
  created_at: number;
  last_used_at?: number | null;
  use_count?: number;
  superseded_by?: string | null;
  [k: string]: unknown;
}
export interface StandingQuery {
  id: string;
  text: string;
  rule: {
    [k: string]: unknown;
  };
  active?: boolean;
  created_at: number;
  [k: string]: unknown;
}
export interface StreamEvent {
  type: "plan" | "clarify" | "evidence" | "answer" | "verified" | "note" | "error" | "done";
  data: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface TrackAttrs {
  color?: string | null;
  color_conf?: number | null;
  upper_color?: string | null;
  lower_color?: string | null;
  vehicle_type?: string | null;
  carrying?: string[];
  size_rel?: number | null;
  is_ir?: boolean;
  [k: string]: unknown;
}
